name: Docker CI/CD Pipeline
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    #df environment variable for tag version
    env:
      DOCKER_REPO: hainammeomeo05 
      IMAGE_TAG: ${{ github.sha }} #dung id commit lam tag
      
    steps:
    - name: 1. Checkout Code
      uses: actions/checkout@v4

    - name: 2. Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: 3. Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push ShortenUrl
      uses: docker/build-push-action@v5
      with:
        context: ./ShortenUrl
        file: ./ShortenUrl/Dockerfile
        push: true
        tags: ${{ env.DOCKER_REPO }}/tinyurlwebapp-shortenurl:${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Build and Push AuthService
      uses: docker/build-push-action@v5
      with:
        context: ./AuthorizeService
        file: ./AuthorizeService/Dockerfile
        push: true
        tags: ${{ env.DOCKER_REPO }}/tinyurlwebapp-authservice:${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and Push Gateway
      uses: docker/build-push-action@v5
      with:
        context: ./Gateway
        file: ./Gateway/Dockerfile
        push: true
        tags: ${{ env.DOCKER_REPO }}/tinyurlwebapp-gateway:${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Build and Push Client
      uses: docker/build-push-action@v5
      with:
        context: ./client/frontend
        file: ./client/frontend/Dockerfile
        push: true
        tags: ${{ env.DOCKER_REPO }}/tinyurlwebapp-client:${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
      
    - name: 5. Deployment Notification (Tùy chọn)
      run: echo "Deployment process completed. Images pushed to Docker Hub with tag ${{ env.IMAGE_TAG }}"